version: 0.0.{build}

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

branches:
  except:
    - gh-pages
    - docs/*

shallow_clone: true
clone_depth: 3

image: Visual Studio 2022

platform:
  - x64

configuration:
  - debug
  # - release

cache:
  - c:/installed/vcpkg-cache
  - c:/tools/vcpkg/downloads

environment:
  VCPKG_ROOT: c:/tools/vcpkg
  VCPKG_DEFAULT_BINARY_CACHE: c:/installed/vcpkg-cache
  VULKAN_SDK: C:/VulkanSDK/1.3.216.0

install:
  # see https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio
  # see https://learn.microsoft.com/en-us/visualstudio/install/workload-and-component-ids
  # see https://learn.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples#using---channeluri
  # $insFolder = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer"
  # $vsFolder = "${env:ProgramFiles}\Microsoft Visual Studio\2022\Community"
  - ps: Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_community.exe" -OutFile "vs_community.exe"
  - ps: ./vs_community.exe --quiet --no-restart --wait --nocache `
        --productId "Microsoft.VisualStudio.Product.Community" `
        --installPath "${env:ProgramFiles}\Microsoft Visual Studio\2022\Community" `
        --channelUri "https://aka.ms/vs/17/release/channel" `
        --installChannelUri "https://aka.ms/vs/17/release/channel" `
        --add Microsoft.VisualStudio.Workload.NativeDesktop `
        --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core `
        --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang `
        --add Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset `
        --add Microsoft.VisualStudio.Component.VC.Modules.x86.x64 `
        --add Microsoft.VisualStudio.ComponentGroup.WindowsAppSDK.Cpp
  # see https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/getting_started.html
  - ps: |
      Push-Location "externals";
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.216.0/windows/VulkanSDK-1.3.216.0-Installer.exe" -OutFile VulkanSDKInstaller.exe;
        ./VulkanSDKInstaller.exe --version
        ./VulkanSDKInstaller.exe --accept-licenses --default-answer --confirm-command install
      Pop-Location;
  - ps: New-Item -Force -Type Directory -Path ${env:VCPKG_DEFAULT_BINARY_CACHE}
  - ps: vcpkg --version
  - ps: vcpkg install --triplet=x64-windows vulkan spdlog directxtk directxtex angle bext-ut

before_build:
  - ps: cmake --preset="x64-windows-${env:configuration}"
  - ps: cmake --build --preset="x64-windows-${env:configuration}" --target gles-ifc

build:
  project: build-x64-windows/gles-test.sln
  parallel: true
  verbosity: normal # detailed

# after_build:
#   - ps: cmake --build --target install --preset="x64-windows-${env:configuration}"

# test_script:
#   - ps: ctest --preset="x64-windows-${env:configuration}"

# artifacts:
#   - path: install
#     name: out-$(platform)-$(configuration)
